// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtShVbZuVlP-eVEPPwlTofNOMQgKpwWRw',
    appId: '1:467755127290:web:a6529ce30c75d4c0ab9443',
    messagingSenderId: '467755127290',
    projectId: 'mobdev-finals-77565',
    authDomain: 'mobdev-finals-77565.firebaseapp.com',
    storageBucket: 'mobdev-finals-77565.appspot.com',
    measurementId: 'G-2DXM0V4VJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClu2Jq560mOdZpfA4Ql1KvTy1alyydOj0',
    appId: '1:467755127290:android:e3daf3aa2bed4e17ab9443',
    messagingSenderId: '467755127290',
    projectId: 'mobdev-finals-77565',
    storageBucket: 'mobdev-finals-77565.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9M11WQJrTjgU8exjc3wV45YkxUdTT6Zc',
    appId: '1:467755127290:ios:8c5093c81bce21c0ab9443',
    messagingSenderId: '467755127290',
    projectId: 'mobdev-finals-77565',
    storageBucket: 'mobdev-finals-77565.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9M11WQJrTjgU8exjc3wV45YkxUdTT6Zc',
    appId: '1:467755127290:ios:0b698b416b138d39ab9443',
    messagingSenderId: '467755127290',
    projectId: 'mobdev-finals-77565',
    storageBucket: 'mobdev-finals-77565.appspot.com',
    iosBundleId: 'com.example.newProject.RunnerTests',
  );
}
